#!/usr/bin/env sh
set -eu

log() {
  printf "%s | %s\n" "$(date -Iseconds)" "$*"
}

# Defaults
PORT="${PORT:-8080}"
HTTPS_PORT="${HTTPS_PORT:-8443}"
PASSWORD_ENV="${PASSWORD:-}"
AGENT_AUTH="${AGENT_AUTH:-}"
AGENT_TLS_CERT="${AGENT_TLS_CERT:-}"
AGENT_TLS_KEY="${AGENT_TLS_KEY:-}"
AGENT_TLS_SELF_SIGNED="${AGENT_TLS_SELF_SIGNED:-}"
AGENT_TLS_DISABLE="${AGENT_TLS_DISABLE:-}"

# Ensure dirs
mkdir -p /data /workspace /srv
chown -R 10001:10001 /data /workspace /srv || true

# Auth/password handling
PASS_FILE="/data/.code-server-password"
AUTH_MODE="password"
if [ -n "$AGENT_AUTH" ]; then
  AUTH_MODE="$AGENT_AUTH"
fi
if [ "$AUTH_MODE" = "none" ]; then
  log "Auth disabled (AGENT_AUTH=none)."
  PASSWORD_VALUE=""
else
  if [ -n "$PASSWORD_ENV" ]; then
    PASSWORD_VALUE="$PASSWORD_ENV"
    log "Using PASSWORD from environment."
  else
    if [ -f "$PASS_FILE" ]; then
      PASSWORD_VALUE="$(cat "$PASS_FILE")"
      log "Loaded PASSWORD from $PASS_FILE."
    else
      # Generate a random 32-char token
      if command -v openssl >/dev/null 2>&1; then
        PASSWORD_VALUE="$(openssl rand -hex 16)"
      else
        # Fallback using /dev/urandom
        PASSWORD_VALUE="$(head -c 24 /dev/urandom | base64 | tr -dc 'A-Za-z0-9' | head -c 32)"
      fi
      printf "%s" "$PASSWORD_VALUE" > "$PASS_FILE"
      chmod 600 "$PASS_FILE"
      log "Generated new PASSWORD and stored at $PASS_FILE."
      log "Autogenerated PASSWORD: $PASSWORD_VALUE"
    fi
  fi
fi

# Render health file
START_TS="$(date -Iseconds)"
cat > /srv/healthz.txt <<EOF
ok
EOF

# Landing page
if [ ! -f /srv/index.html ]; then
  cat > /srv/index.html <<HTML
<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>GuildNet Agent</title>
  <style>
    body { font-family: system-ui, -apple-system, Segoe UI, Roboto, sans-serif; margin: 2rem; color: #222; }
    .card { border: 1px solid #ddd; border-radius: 8px; padding: 1rem; max-width: 720px; }
    a { color: #0b5fff; text-decoration: none; }
    a:hover { text-decoration: underline; }
    .muted { color: #666; font-size: 0.9rem; }
  </style>
</head>
<body>
  <div class="card">
    <h1>GuildNet Agent</h1>
    <p class="muted">Start: ${START_TS}</p>
    <ul>
      <li><a href="/">Open VS Code (code-server)</a></li>
      <li><a href="/healthz">Health</a></li>
    </ul>
    <p class="muted">Default port: ${PORT}</p>
  </div>
</body>
</html>
HTML
fi

# Start code-server (listen on loopback only), workspace at /workspace
CODE_SERVER_ADDR="127.0.0.1:8080"

log "Starting code-server on ${CODE_SERVER_ADDR}, proxy http:${PORT} https:${HTTPS_PORT}, workspace /workspace, auth=${AUTH_MODE}"

CODE_SERVER_CMD="code-server --bind-addr ${CODE_SERVER_ADDR} \
  --user-data-dir /data/user-data \
  --extensions-dir /data/extensions \
  --disable-telemetry \
  --auth ${AUTH_MODE} /workspace"

# Export PASSWORD for code-server if using password auth
if [ "$AUTH_MODE" = "password" ]; then
  export PASSWORD="$PASSWORD_VALUE"
fi

# Trap and forward signals
PIDS=""
term() {
  log "Shutting down..."
  # shellcheck disable=2086
  [ -n "$PIDS" ] && kill $PIDS 2>/dev/null || true
}
trap term INT TERM

# Start code-server
sh -c "$CODE_SERVER_CMD" &
PID_CODE=$!
PIDS="$PIDS $PID_CODE"

# Prepare Caddyfile (support HTTPS with provided or self-signed certs)
CADDYFILE="/tmp/Caddyfile.generated"

# HTTPS defaults: enable by default. If no cert/key specified, create self-signed under /data/tls.
if [ -z "$AGENT_TLS_DISABLE" ] || [ "$AGENT_TLS_DISABLE" = "0" ]; then
  AGENT_TLS_DIR="/data/tls"
  mkdir -p "$AGENT_TLS_DIR"
  # If paths not provided, default to /data/tls/*
  if [ -z "$AGENT_TLS_CERT" ] || [ -z "$AGENT_TLS_KEY" ]; then
    AGENT_TLS_CERT="${AGENT_TLS_CERT:-$AGENT_TLS_DIR/agent.crt}"
    AGENT_TLS_KEY="${AGENT_TLS_KEY:-$AGENT_TLS_DIR/agent.key}"
  fi
  # Ensure files exist: generate self-signed when missing
  if [ ! -f "$AGENT_TLS_CERT" ] || [ ! -f "$AGENT_TLS_KEY" ]; then
    log "Generating self-signed TLS cert for agent..."
    openssl req -x509 -nodes -newkey rsa:2048 \
      -subj "/CN=localhost" \
      -days 3650 \
      -keyout "$AGENT_TLS_KEY" \
      -out "$AGENT_TLS_CERT" >/dev/null 2>&1 || true
  fi
else
  log "HTTPS disabled by AGENT_TLS_DISABLE=1"
fi

{
  cat > "$CADDYFILE" <<CADDY
{
  admin off
}

# HTTP listener (always on)
:{$PORT} {
  encode zstd gzip

  header {
    -X-Frame-Options
    Content-Security-Policy "frame-ancestors 'self' *"
    Referrer-Policy "no-referrer"
    X-Content-Type-Options "nosniff"
  }

  @health path /healthz
  handle @health {
    root * /srv
    file_server
    try_files {path} /healthz.txt
  }

  @landing path /landing
  handle @landing {
    root * /srv
    file_server
    try_files {path} /index.html
  }

  handle {
    reverse_proxy 127.0.0.1:8080
  }
}
CADDY
}

# HTTPS listener (default on) when cert and key exist
if [ -n "$AGENT_TLS_CERT" ] && [ -n "$AGENT_TLS_KEY" ] && [ -f "$AGENT_TLS_CERT" ] && [ -f "$AGENT_TLS_KEY" ] && { [ -z "$AGENT_TLS_DISABLE" ] || [ "$AGENT_TLS_DISABLE" = "0" ]; }; then
  {
    cat >> "$CADDYFILE" <<CADDY

:{$HTTPS_PORT} {
  encode zstd gzip
  tls {$AGENT_TLS_CERT} {$AGENT_TLS_KEY}

  header {
    -X-Frame-Options
    Content-Security-Policy "frame-ancestors 'self' *"
    Referrer-Policy "no-referrer"
    X-Content-Type-Options "nosniff"
  }

  @health path /healthz
  handle @health {
    root * /srv
    file_server
    try_files {path} /healthz.txt
  }

  @landing path /landing
  handle @landing {
    root * /srv
    file_server
    try_files {path} /index.html
  }

  handle {
    reverse_proxy 127.0.0.1:8080
  }
}
CADDY
  }
  log "HTTPS enabled on port ${HTTPS_PORT} (cert=$AGENT_TLS_CERT)"
else
  log "HTTPS not enabled (either disabled or cert/key missing)."
fi

# Start Caddy serving /healthz and reverse proxy to code-server
caddy run --config "$CADDYFILE" --adapter caddyfile &
PID_CADDY=$!
PIDS="$PIDS $PID_CADDY"

# Wait on children; if either exits, exit
# POSIX-friendly loop: exit when any child dies
STATUS=0
while :; do
  if ! kill -0 "$PID_CODE" 2>/dev/null; then
    STATUS=1
    break
  fi
  if ! kill -0 "$PID_CADDY" 2>/dev/null; then
    STATUS=1
    break
  fi
  sleep 1
done
term
wait || true
exit $STATUS
