apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostapp
spec:
  template:
    spec:
      containers:
        - name: hostapp
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /api/db/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10